"""Provider lifecycle, cost guard, and fail-closed fallback contracts."""

from .alert_engine import (
    ProviderAlertEngine,
    ProviderAlertEvaluation,
    ProviderAlertTransition,
    ProviderAlertTransitionState,
    StaleProviderAlertEvidenceError,
)
from .notification_gateway import (
    NotificationDispatcher,
    ProviderNotificationDispatch,
    ProviderNotificationGateway,
)
from .shadow_validation import (
    ProviderAlertShadowBatch,
    ProviderAlertShadowEvent,
    ProviderAlertShadowSummary,
    ProviderAlertShadowValidator,
)
from .contract import (
    CostAction,
    CostGuardDecision,
    DataAdmission,
    FallbackAssessment,
    FallbackQualityChecks,
    GuardSeverity,
    ProviderAlert,
    ProviderGuardAssessment,
    ProviderHealthState,
    ProviderLifecycleRecord,
    ProviderRole,
    assess_provider,
    evaluate_cost_action,
    evaluate_fallback,
)
from .observer import (
    EvidenceConflictError,
    EvidenceProvenance,
    ObservedProviderValue,
    ProviderRuntimeObservation,
    ProviderRuntimeObserver,
    RuntimeProviderSnapshot,
)
from .runtime_ingest import (
    ProviderRuntimeIngestError,
    build_alpaca_observation_from_runtime_events,
    build_cn_provider_observations_from_cloud_snapshot,
    build_moomoo_opend_observation_from_livefeed_heartbeat,
    build_negative_provider_probe_observation,
    ingest_alpaca_runtime_events,
    ingest_cn_cloud_observation,
    ingest_moomoo_opend_livefeed_heartbeat,
    ingest_negative_provider_probe,
)
from .registry import (
    DEFAULT_PROVIDER_REGISTRY,
    ProviderDefinition,
    get_provider_definition,
)

__all__ = [
    "DEFAULT_PROVIDER_REGISTRY",
    "CostAction",
    "CostGuardDecision",
    "DataAdmission",
    "EvidenceConflictError",
    "EvidenceProvenance",
    "FallbackAssessment",
    "FallbackQualityChecks",
    "GuardSeverity",
    "ObservedProviderValue",
    "ProviderAlert",
    "ProviderAlertEngine",
    "ProviderAlertEvaluation",
    "ProviderAlertTransition",
    "ProviderAlertTransitionState",
    "ProviderAlertShadowBatch",
    "ProviderAlertShadowEvent",
    "ProviderAlertShadowSummary",
    "ProviderAlertShadowValidator",
    "NotificationDispatcher",
    "ProviderNotificationDispatch",
    "ProviderNotificationGateway",
    "ProviderDefinition",
    "ProviderGuardAssessment",
    "ProviderHealthState",
    "ProviderLifecycleRecord",
    "ProviderRole",
    "ProviderRuntimeIngestError",
    "ProviderRuntimeObservation",
    "ProviderRuntimeObserver",
    "RuntimeProviderSnapshot",
    "StaleProviderAlertEvidenceError",
    "assess_provider",
    "build_alpaca_observation_from_runtime_events",
    "build_cn_provider_observations_from_cloud_snapshot",
    "build_moomoo_opend_observation_from_livefeed_heartbeat",
    "build_negative_provider_probe_observation",
    "evaluate_cost_action",
    "evaluate_fallback",
    "get_provider_definition",
    "ingest_alpaca_runtime_events",
    "ingest_cn_cloud_observation",
    "ingest_moomoo_opend_livefeed_heartbeat",
    "ingest_negative_provider_probe",
]
