"""Provider lifecycle, cost guard, and fail-closed fallback contracts."""

from .alerts import (
    NotificationServiceProviderGuardSink,
    ProviderGuardAlertEngine,
    ProviderGuardNotification,
    format_provider_guard_notification,
    provider_guard_structured_payload,
)
from .contract import (
    CostAction,
    CostGuardDecision,
    DataAdmission,
    FallbackAssessment,
    FallbackQualityChecks,
    GuardSeverity,
    ProviderAlert,
    ProviderGuardAssessment,
    ProviderHealthState,
    ProviderLifecycleRecord,
    ProviderRole,
    assess_provider,
    evaluate_cost_action,
    evaluate_fallback,
)
from .observer import (
    EvidenceConflictError,
    EvidenceProvenance,
    ObservedProviderValue,
    ProviderRuntimeObservation,
    ProviderRuntimeObserver,
    RuntimeProviderSnapshot,
)
from .runtime_ingest import (
    ProviderRuntimeIngestError,
    build_alpaca_observation_from_runtime_events,
    build_cn_provider_observations_from_cloud_snapshot,
    build_moomoo_opend_observation_from_livefeed_heartbeat,
    build_negative_provider_probe_observation,
    ingest_alpaca_runtime_events,
    ingest_cn_cloud_observation,
    ingest_moomoo_opend_livefeed_heartbeat,
    ingest_negative_provider_probe,
)
from .registry import (
    DEFAULT_PROVIDER_REGISTRY,
    ProviderDefinition,
    get_provider_definition,
)

__all__ = [
    "DEFAULT_PROVIDER_REGISTRY",
    "CostAction",
    "CostGuardDecision",
    "DataAdmission",
    "EvidenceConflictError",
    "EvidenceProvenance",
    "FallbackAssessment",
    "FallbackQualityChecks",
    "GuardSeverity",
    "NotificationServiceProviderGuardSink",
    "ObservedProviderValue",
    "ProviderAlert",
    "ProviderDefinition",
    "ProviderGuardAssessment",
    "ProviderGuardAlertEngine",
    "ProviderGuardNotification",
    "ProviderHealthState",
    "ProviderLifecycleRecord",
    "ProviderRole",
    "ProviderRuntimeIngestError",
    "ProviderRuntimeObservation",
    "ProviderRuntimeObserver",
    "RuntimeProviderSnapshot",
    "assess_provider",
    "build_alpaca_observation_from_runtime_events",
    "build_cn_provider_observations_from_cloud_snapshot",
    "build_moomoo_opend_observation_from_livefeed_heartbeat",
    "build_negative_provider_probe_observation",
    "evaluate_cost_action",
    "evaluate_fallback",
    "get_provider_definition",
    "format_provider_guard_notification",
    "ingest_alpaca_runtime_events",
    "ingest_cn_cloud_observation",
    "ingest_moomoo_opend_livefeed_heartbeat",
    "ingest_negative_provider_probe",
    "provider_guard_structured_payload",
]
